### ISSUE TITLE
hey, it's not working anymore

### ISSUE THREAD

**Issue by souhaiebtar** [DONSA/symfonycasts-downloader#10]

**Comment by n3s7or** [comment]
Can you give a try to my [script](https://github.com/n3s7or/symfonycasts-scraper). Author haven't made any commit since a long time anyway.
Sorry if spamming :)

**Comment by souhaiebtar** [comment]
> Can you give a try to my [script](https://github.com/n3s7or/symfonycasts-scraper). Author haven't made any commit since a long time anyway.
> Sorry if spamming :)

thanks for the reply, i will do it as soon as possible
