### ISSUE TITLE
work only a single time

### ISSUE THREAD

**Issue by souhaiebtar** [DONSA/symfonycasts-downloader#12]
it report that 
```
Client error: `POST https://symfonycasts.com/login_check` resulted in a `429 Too
   Many Requests` response:
  error code: 1015
```

**Comment by Kalianey** [comment]
I have the same message, it doesn't work at all: 
`In RequestException.php line 113:
                                                                               
  Client error: `POST https://symfonycasts.com/login_check` resulted in a `42  
  9 Too Many Requests` response:                                               
  error code: 1015   `

**Comment by souhaiebtar** [comment]
@Kalianey this limitation is set in symfonyCasts website on how much request that can be received from a single ip,
