### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lucas-marx** [DONSA/symfonycasts-downloader#13]
I've cloned the repository but its not working here, im getting 

> PHP Fatal error:  require(): Failed opening required '/home/lucas/Apps/symfonycasts-downloader/src/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/lucas/Apps/symfonycasts-downloader/src/console on line 8

what am I doing wrong?

the readme could have some more information on the steps of use and how to filter the courses.

**Comment by DONSA** [comment]
Did you run `composer install`?
Did you `cp src/application.ini src/local.ini` and added your credentials? In that file you can find a commented out section explaining how to filter out the courses that you want to download.

**Comment by lucas-marx** [comment]
Only added the credentials in one file, now its working fine, sorry about that. Thanks!
